repositories:
  leethomason/tinyxml2:
    type: git
    url: https://github.com/leethomason/tinyxml2.git
    version: master
  jbeder/yaml-cpp:
    type: git
    url: https://github.com/jbeder/yaml-cpp.git
    version: master