name: build

on: [push, pull_request]

jobs:
  build:
  strategy:
      matrix:
        android-abi: [armeabi-v7a, arm64-v8a]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker login
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
    - name: build
      run: |
        export ANDROID_ABI=${{ matrix.android-abi }}
        ./docker_run.sh ./import-src.sh
        ./docker_build.sh
        ./pack.sh
    - uses: actions/upload-artifact@v2
      with:
        name: librosbag2-dev-${{ matrix.android-abi }}
        path: release/${{ matrix.android-abi }}/librosbag2-dev-${{ matrix.android-abi }}.tar.gz
